apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: house-management-data
  namespace: house-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
